### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by nthanhtung92** [phamvinhnga/telegram_ocean_auto_claim#2]
Chào bác, 
![image](https://github.com/phamvinhnga/telegram_ocean_auto_claim/assets/168674000/a4d935a2-239f-4e40-be17-4a9a2338f626)
mình chạy bị lỗi như này, bác kiểm tra giúp nhé
cảm ơn bác

**Comment by ngaphaminfodation** [comment]
Uả? Sác bác biết project của em. Bác import exentsion vào là dùng dc thôi mà.

**Comment by nthanhtung92** [comment]
E chạy được rồi, cảm ơn bác nhé

**Comment by nthanhtung92** [comment]
à bác ơi, bác xem làm auto claim Hot bên mạng Near được không bác?
nó cũng tương tự Ocean.
link dự án -> [https://t.me/herewalletbot)](https://t.me/herewalletbot/app?startapp=7127483-village-169022)
em không biết liên hệ bác ở đâu nên đành nhắn vào đây. Có gì bác nhắn em qua tele: tupacrypto nhé
